---
title: "classification"
author: "Mehdi Ghane"
date: "October 24, 2019"
output: html_document
---

```{r setup, include=FALSE}
options(java.parameters = "-Xmx6g")
library(XLConnect)
library(rJava)
library(xlsx)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(lattice)
library(scales)
library(plotly)
library(htmlwidgets)
library(data.table)
library(stats)
library(mosaic)
library(tidyselect)
setwd("C:/Users/Mehdi/Desktop/Desktop/Data Science/Projects/reCLAIM/classification_comp_starter_kit")
train <- fread("./Header - train.csv", na.strings = c("Unspecified","Not Available"))
validation <- fread("./Header - validation.csv", na.strings = c("Unspecified","Not Available"))
##test <- fread("./Header - test.csv", na.strings = c("Unspecified","Not Available"))
wctrain <- fread("./Well_class_train.csv", na.strings = c("Unspecified","Not Available"))
wcvalidation <- fread("./Well_class_validate.csv", na.strings = c("Unspecified","Not Available"))
tall <- tally(group_by(train,Province, Formation, Pool, Field), sort = TRUE, na.rm=T)
##nr <- contains("Viking", ignore.case = TRUE, vars = train$Formation)
##nr <- c(nr,contains("Viking Formation", ignore.case = TRUE, vars = train$Formation))
##ftrain <- train[nr,]
merged <- rbind(train,validation)
wcmerged <- rbind(wctrain,wcvalidation)
count(isTRUE(duplicated(merged$EPAssetsId)))
count(isTRUE(duplicated(wcmerged$EPAssetsId)))
##df <- merge(ftrain, mviking, by="EPAssetsId", all = TRUE)
df <- mutate(merged, Hlength = TotalDepth - TVD)
df <- mutate(df, Hlength2 = sqrt((Surf_Longitude-BH_Longitude)^2+(Surf_Latitude-BH_Latitude)^2))
nrn <- count(is.na(df$Hlength))
nrn2 <- count(is.na(df$Hlength2))
count(df$Hlength<0)
min(df$Hlength,na.rm = TRUE)
df$Hlength[which(df$Hlength<0)] <-   NA
favstats(df$Hlength)
quantile(df$Hlength, c(0,0.01,0.05,0.1,0.25,0.5,0.75,1), na.rm = T)
df <- merge(df, wcmerged, by="EPAssetsId", all = TRUE)
head <- colnames(df)
head[87] <- "MaxOil_BOE"
head[88] <- "Frac_Stages"
head[89] <- "OpenHole"
head[90] <- "Comp_Events"
colnames(df) <- head
# working with data
df$LicenceDate <- as.Date(df$LicenceDate, format = "%m/%d/%Y") ; df$SpudDate <- as.Date(df$SpudDate, format = "%m/%d/%Y"); df$RigReleaseDate <- as.Date(df$RigReleaseDate, format = "%m/%d/%Y"); df$StatusDate <- as.Date(df$StatusDate, format = "%m/%d/%Y")
df$TimeDiff_Now_Status <- as.numeric(Sys.Date() - df$StatusDate)
df$TimeDiff_Status_RigRelease <- as.numeric(df$StatusDate - df$RigReleaseDate)
df$TimeDiff_Nows_RigRelease <- as.numeric(Sys.Date() - df$RigReleaseDate)
df$TimeDiff_RigRelease_Spud <- as.numeric(df$RigReleaseDate-df$SpudDate)
# Group_by the data to calculate median for well status
df <- df %>% group_by(WellTypeStandardised) %>% mutate(Md_time_diff=median(TimeDiff_Now_Status, na.rm = TRUE)) %>% arrange(Md_time_diff)
dff <- df[which(df$DaysDrilling<40 & df$TimeDiff_RigRelease_Spud>0),]
knitr::opts_chunk$set(echo = TRUE)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(df$DaysDrilling,df$TimeDiff_RigRelease_Spud)
par(mfrow=c(2,1), mar=c(4,3,1,2), oma=c(0,0,3,0))
fdf <- filter(df, WellSymbPt1==c("Oil"))
hist(df$Hlength, col = "Blue")
hist(df$Hlength2, col = factor(df$Province))
# Plot for time diff (Status - Current)
qplot(well_status, TimeDiff_Now_Status, data = dff, geom = "boxplot")
qplot(well_status, Md_time_diff, data = dff, geom = "boxplot")
qplot(TimeDiff_Now_Status, data = dff, bins=100, fill=well_status, facets =well_status~.)
# Plot for time diff (Status - Current)
qplot(well_status, TimeDiff_Nows_RigRelease, data = dff, geom = "boxplot")
qplot(TimeDiff_Nows_RigRelease, data = dff, bins=100, fill=well_status, facets =well_status~.)
# Plot for time diff (Status - Rigrelease)
qplot(well_status,TimeDiff_Status_RigRelease, data = dff, geom = "boxplot")
#qplot(well_status, Md_time_diff, data = df, geom = "boxplot")
qplot(TimeDiff_Status_RigRelease, data = dff, bins=100, fill=well_status, facets =well_status~.)
##
qplot(well_status,Comp_Events, data =dff, geom ="boxplot", ylim = c(-10,50))
qplot(Comp_Events/(DaysDrilling), data = dff, bins=100 ,fill=well_status,ylim = c(0,1000) ,xlim = c(0,10), facets =well_status~.)
qplot(well_status,DaysDrilling , data =dff, geom ="boxplot")
qplot(DaysDrilling, data = dff, bins=100, fill=well_status, facets =well_status~.)
qplot(DaysDrilling, data = df, bins=100, fill=well_status, facets =well_status~.) ## no filter
##
ggplot(data = dff, aes(y = MaxOil_BOE, x = Hlength)) + geom_point(col="blue",size = 2,position = "jitter") +xlim(c(1,2000))+ylim(c(1,500)) + ylab("Max Oil") + xlab("Horizontal Length") + ggtitle("Scatterplot")
##ggplot(data = df, aes(y = Norm_Oil, x = Hlength2)) + geom_point(col="blue",size = 2,position = "jitter") +xlim(c(0,0.05))+ylim(c(1,100))
qplot(dff$TimeDiff_Now_Status, data = dff, bins=20, binwidth=2, facets = well_status ~.)
qplot(dff$WellSymbPt1, Hlength2, data = dff, geom = "boxplot")
qplot(TimeDiff_Now_Status, Hlength, data = dff, color=WellSymbPt1, shape=WellSymbPt1,facets = WellSymbPt1~.) + geom_smooth(method = "lm")
qplot(Hlength2,Comp_Events,data = dff, color=well_status, shape=WellSymbPt1) + geom_smooth(method = "lm")
#qplot(Norm_Gas, Norm_Water, data = fdf, color=WellSymbPt1, shape=WellSymbPt1) + geom_smooth(method = "lm") +ylim(c(0,50)) + xlim(c(0,50))
qplot(WellTypeStandardised,TimeDiff_Now_Status, data = dff, geom = "boxplot")

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
